---
- name: Ensure compose project directory exists
  ansible.builtin.file:
    path: "{{ compose_echo_project_dir }}"
    state: directory
    mode: '0755'

- name: Copy docker compose
  ansible.builtin.template:
    src: "docker-compose.yaml.j2"
    dest: "{{ compose_echo_project_dir }}/docker-compose.yaml"
    mode: '0644'

- name: Docker Compose Up
  community.docker.docker_compose_v2:
    project_src: "{{ compose_echo_project_dir }}"
