---
- name: Ensure compose project directory exists
  ansible.builtin.file:
    path: "{{ compose_base_project_dir }}"
    state: directory
    mode: '0755'

- name: Copy docker compose configs
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ compose_base_project_dir }}/{{ item }}"
    mode: '0644'
  loop: "{{ compose_base_compose_files }}"

- name: Copy main docker compose config
  ansible.builtin.template:
    src: "docker-compose.yaml.j2"
    dest: "{{ compose_base_project_dir }}/docker-compose.yaml"
    mode: '0644'

- name: Ensure prometheus configs exists
  ansible.builtin.include_tasks: prometheus.yml

- name: Ensure alertmanager configs exists
  ansible.builtin.include_tasks: alertmanager.yml

- name: Ensure traefik configs exists
  ansible.builtin.include_tasks: traefik.yml

- name: Docker Compose Up
  community.docker.docker_compose_v2:
    project_src: "{{ compose_base_project_dir }}"
  register: docker_compose
