---
compose_base_project_dir: /opt/compose-base

compose_base_compose_files:
  - compose-prometheus.yaml.j2
  - compose-traefik.yaml.j2

compose_base_traefik_config_dir: "{{ compose_base_project_dir }}/traefik"
compose_base_traefik_image_url: traefik
compose_base_traefik_image_tag: v3.0

compose_base_prometheus_config_dir: "{{ compose_base_project_dir }}/prometheus"
compose_base_prometheus_image_url: "prometheus/prometheus"
compose_base_prometheus_image_tag: "latest"
compose_base_prometheus_host: "prometheus.localhost"
