---
compose_base_project_dir: /opt/compose-base

compose_base_compose_files:
  - compose-prometheus.yaml
  - compose-traefik.yaml
  - compose-exporters.yaml

compose_base_traefik_config_dir: "{{ compose_base_project_dir }}/traefik"
compose_base_traefik_image_url: traefik
compose_base_traefik_image_tag: v3.0

compose_base_prometheus_config_dir: "{{ compose_base_project_dir }}/prometheus"
compose_base_prometheus_image_url: "prom/prometheus"
compose_base_prometheus_image_tag: "latest"
compose_base_prometheus_host: "prometheus.localhost"
compose_base_prometheus_users: "prometheus:$2y$10$LwA4BD7M/6X42.EzryolduOi2kDxGXWLgujV.V1Ze9V1pR./brpNS,"
compose_base_prometheus_web_path_prefix: "/p"

compose_base_cadvisor_image_url: gcr.io/cadvisor/cadvisor
compose_base_cadvisor_image_tag: v0.49.1

compose_base_node_exporter_image_url: quay.io/prometheus/node-exporter
compose_base_node_exporter_image_tag: v1.8.1
