---
compose_base_project_dir: /opt/compose-base

compose_base_compose_files:
  - compose-prometheus.yaml
  - compose-traefik.yaml
  - compose-exporters.yaml

compose_base_traefik_config_dir: "{{ compose_base_project_dir }}/traefik"
compose_base_traefik_image_url: traefik
compose_base_traefik_image_tag: v3.0
compose_base_traefik_cloudflare_token: ""
compose_base_traefik_certresolver: "http01"

compose_base_prometheus_config_dir: "{{ compose_base_project_dir }}/prometheus"
compose_base_prometheus_image_url: "prom/prometheus"
compose_base_prometheus_image_tag: "latest"
compose_base_prometheus_host: "prometheus.localhost"
compose_base_prometheus_users: "prometheus:$2y$10$LwA4BD7M/6X42.EzryolduOi2kDxGXWLgujV.V1Ze9V1pR./brpNS"
compose_base_prometheus_web_path_prefix: "/p"
compose_base_prometheus_labels:
  traefik.enable: "true"
  traefik.http.routers.prometheus.rule: "Host(`{{ compose_base_prometheus_host }}`) && PathPrefix(`{{ compose_base_prometheus_web_path_prefix }}`)"
  traefik.http.routers.prometheus.entrypoints: "https"
  traefik.http.routers.prometheus.tls: "true"
  traefik.http.routers.prometheus.tls.certresolver: "{{ compose_base_traefik_certresolver }}"
  traefik.http.routers.prometheus.middlewares: prometheus-auth
  traefik.http.services.prometheus.loadbalancer.server.port: "9090"
  traefik.http.middlewares.prometheus-auth.basicauth.users: "{{ compose_base_prometheus_users | replace('$', '$$') }}"
  traefik.docker.network: "traefik"
compose_base_prometheus_host_name: "{{ inventory_hostname }}"

compose_base_alertmanager_config_dir: "{{ compose_base_project_dir }}/alertmanager"
compose_base_alertmanager_image_url: "prom/alertmanager"
compose_base_alertmanager_image_tag: "latest"
compose_base_alertmanager_host: "alertmanager.localhost"
compose_base_alertmanager_users: "{{ compose_base_prometheus_users }}"
compose_base_alertmanager_web_path_prefix: "/a"
compose_base_alertmanager_labels:
  traefik.enable: "true"
  traefik.http.routers.alertmanager.rule: "Host(`{{ compose_base_alertmanager_host }}`) && PathPrefix(`{{ compose_base_alertmanager_web_path_prefix }}`)"
  traefik.http.routers.alertmanager.entrypoints: "https"
  traefik.http.routers.alertmanager.tls: "true"
  traefik.http.routers.alertmanager.tls.certresolver: "{{ compose_base_traefik_certresolver }}"
  traefik.http.routers.alertmanager.middlewares: alertmanager-auth
  traefik.http.services.alertmanager.loadbalancer.server.port: "9093"
  traefik.http.middlewares.alertmanager-auth.basicauth.users: "{{ compose_base_alertmanager_users | replace('$', '$$') }}"
  traefik.docker.network: "traefik"


compose_base_cadvisor_image_url: gcr.io/cadvisor/cadvisor
compose_base_cadvisor_image_tag: v0.49.1

compose_base_node_exporter_image_url: quay.io/prometheus/node-exporter
compose_base_node_exporter_image_tag: v1.8.1
